### ISSUE TITLE
Usuwanie faktur sprzedaży

### ISSUE THREAD

**Issue by eredzik** [eredzik/vatcalc#25]

**Comment by eredzik** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add option to select current enterprise](https://trello.com/c/M8rJVWhC/22-add-option-to-select-current-enterprise)

**Comment by hawkesky** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add feature to remove invoices](https://trello.com/c/KepiOSEv/27-add-feature-to-remove-invoices)
